### PR TITLE
Fixing #699  java.lang.SecurityException

### LINKED ISSUE #699: java.lang.SecurityException: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified
[Newly introduced behavior changes in Android 14](https://developer.android.com/about/versions/14/behavior-changes-14) causes Maverick to crash the app.

image

... 75 more
Caused by: java.lang.SecurityException: com.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
at android.os.Parcel.createExceptionOrNull([Parcel.java:3057](http://parcel.java:3057/))
at android.os.Parcel.createException([Parcel.java:3041](http://parcel.java:3041/))
at android.os.Parcel.readException([Parcel.java:3024](http://parcel.java:3024/))
at android.os.Parcel.readException([Parcel.java:2966](http://parcel.java:2966/))
at [android.app](http://android.app/).IActivityManager$Stub$Proxy.registerReceiverWithFeature([IActivityManager.java:5684](http://iactivitymanager.java:5684/))
at [android.app](http://android.app/).ContextImpl.registerReceiverInternal([ContextImpl.java:1852](http://contextimpl.java:1852/))
at [android.app](http://android.app/).ContextImpl.registerReceiver([ContextImpl.java:1792](http://contextimpl.java:1792/))
at [android.app](http://android.app/).ContextImpl.registerReceiver([ContextImpl.java:1780](http://contextimpl.java:1780/))
at android.content.ContextWrapper.registerReceiver([ContextWrapper.java:755](http://contextwrapper.java:755/))
at com.airbnb.mvrx.mocking.printer.MavericksPrintStateBroadcastReceiver.register(MavericksMockPrinter.kt:207)
at com.airbnb.mvrx.mocking.MockMavericksViewModelConfigFactory.buildConfig(MockableMavericksViewModelConfig.kt:273)
at com.airbnb.mvrx.MavericksViewModelConfigFactory.provideConfig$mvrx_release(MavericksViewModelConfigFactory.kt:67)
at com.airbnb.mvrx.MavericksViewModel.<init>(MavericksViewModel.kt:35)
at com.airbnb.mvrx.MavericksViewModel.<init>(MavericksViewModel.kt:25)

This happens due to the following line: https://github.com/airbnb/mavericks/blob/1318087ee6fea40d1d2e0b5a0b34f36c19a297dd/mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt#L207

### PR DESCRIPTION
**Pull request by danpe**
Fixes #699

### CODE REVIEW

File: mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt [hunk 1]
```diff
@@ -204,6 +205,11 @@ internal abstract class MavericksPrintStateBroadcastReceiver : BroadcastReceiver
     fun register(context: Context) {
         check(!isRegistered) { "Already registered" }
         isRegistered = true
+        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
+            context.registerReceiver(networkInfoReceiver, filter, Context.RECEIVER_NOT_EXPORTED)
```
Comment (elihart) [inline mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt:209]: @danpe thanks for fixing, but this doesn't seem to compile
```
MavericksMockPrinter.kt:209:38 Unresolved reference: networkInfoReceiver
```

Comment (elihart) [reply mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt:209]: I think you need to do what `context.registerReceiver(this, IntentFilter(ACTION_COPY_MAVERICKS_STATE))` does below? and that line should be replaced with this new code

Comment (danpe) [reply mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt]: Thank you my bad, fixed it.

Comment (elihart) [reply mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt]: Good to know, but since this is the mocking library it shouldn't be running in production. Do you need to change your configuration?

**Comment by danpe** [comment]
Thank you! Can you also make a release please? 🙏

**Comment by elihart** [comment]
I can make a release next week. I'm still curious though, if you are seeing these crashes in production, if you should instead be changing your config to not run the mock printer code in prod builds

File: mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt (hunk 1 above)
Comment (danpe) [reply mvrx-mocking/src/main/kotlin/com/airbnb/mvrx/mocking/printer/MavericksMockPrinter.kt]: It is weird as even if I disable mocking completely it still crashes,
```
        MockableMavericks.initialize(
            mocksEnabled =false
            debugMode = false,
            applicationContext = this,
            //TODO maybe use other dispatchers
            viewModelCoroutineContext = Dispatchers.Default,
            stateStoreCoroutineContext = Dispatchers.Default
        )
```

Still crashes on startup...

**Comment by elihart** [comment]
That doesn't control the mock printer configuration. You must be calling `registerMockPrinter` somewhere in your app. Don't call it in production builds...

**Comment by danpe** [comment]
> That doesn't control the mock printer configuration. You must be calling `registerMockPrinter` somewhere in your app. Don't call it in production builds...

Tbh, we don't call `registerMockPrinter` anywhere in our app, that why it is strange.

**Comment by elihart** [comment]
It seems like you'll want to figure out the root cause of why the mock printer is registering in your production app. Even if you apply this fix you still don't want the broadcast receiver starting in your prod app.

Look at how you might be using `MockableMavericks.enableMockPrinterBroadcastReceiver`, or manual instantiation of MavericksMockPrinter

**Comment by danpe** [comment]
Hi @elihart , thank you for responding.
TBH, I did `Find All.. (Cmd+Shift+F)` and tried looking for both `enableMockPrinterBroadcastReceiver` and `MavericksMockPrinter` in all my files and modules.

Nothing found.

**Comment by mlengy** [comment]
Hi @elihart, thanks for the fix. Currently running into this issue when attempting to target API 34 as well. Curious when a new release would be possible. Thanks!

**Comment by ArunYogeshwaran** [comment]
Thanks for this fix. It helped us when we upgraded our target SDK version to 34
